---
- name: Setup System for Remix File Hosting
  hosts: localhost

### Play to get system ready for creating Fedora Remixes
### Designed to be run from localhost

  vars:
    fedora_boot_files:
      - vmlinuz
      - initrd.img
    fedora_version: 38
  tasks:


## Create Directories

    - name: Install Packages for UCF Building
      ansible.builtin.yum:
        name: httpd
        state: latest
      become: true

    - name: Copy Files to Web Directory
      ansible.posix.synchronize:
        src: ./files
        dest: /var/www/html
      become: true

    - name: Copy Boot Theme to Web Directory
      ansible.posix.synchronize:
        src: ./files/boot/tm-fedora-remix
        dest: /var/www/html
      become: true  

    - name: Create Apache Configuration
      ansible.posix.synchronize:
        src: ./files/httpd_index.conf
        dest: /etc/httpd/conf.d/httpd_index.conf
      become: true

    - name: Create FedoraRemixCustomize Directory
      ansible.builtin.git:
        repo: https://github.com/tmichett/FedoraRemixCustomize.git
        dest: /var/www/html/FedoraRemixCustomize
      become: true

    - name: Create FedoraRemixPXE Directory
      ansible.builtin.git:
        repo: https://github.com/tmichett/PXEServer.git
        dest: /var/www/html/PXEServer
      become: true


## Create PXE Boot Files directory
    - name: Create the Remix Directories for PXEBoot
      ansible.builtin.file:
        path: /var/www/html/FedoraRemixPXE
        state: directory
        mode: '0755'
      become: true

## Obtain Boot images for PXEBoot
    - name: Download Boot Images for PXEBoot
      ansible.builtin.get_url:
        url:  https://download.fedoraproject.org/pub/fedora/linux/releases/{{ fedora_version }}/Server/x86_64/os/images/pxeboot/{{ item }}
        dest: /var/www/html/FedoraRemixPXE/
      loop: "{{ fedora_boot_files }}"

    - name: Create and Synchronize Scripts Directory
      ansible.posix.synchronize:
        src: ../YAD/scripts
        dest: /var/www/html/
      become: true

    - name: Copy YAD Files
      ansible.posix.synchronize:
        src: ../YAD/{{ item }}
        dest: /var/www/html
      become: true
      loop: 
        - Fedora_Remix_Apps.desktop
        - Fedora_Remix_Customize.sh


    - name: Enable HTTPD Service
      ansible.builtin.systemd:
        name: httpd
        enabled: true
        state: started
      become: true
