---
- name: Setup System for Remix Creation and Building
  hosts: localhost
  vars:
    remix_packages:
      - vim
      - livecd-tools
        #      - spin-kickstarts
      - sshfs
    remix_directories:
      - /livecd-creator/FedoraRemix
      - /livecd-creator/package-cache

### Play to get system ready for creating Fedora Remixes
### Designed to be run from localhost


  tasks:


## Create Directories

    - name: Install Packages for UCF Building
      ansible.builtin.yum:
        name: "{{ remix_packages }}"
        state: latest
      become: true

    - name: Create the Remix Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ remix_directories }}"
      become: true

## Copy Kickstart files

    - name: Fedora Kickstart Files
      ansible.posix.synchronize:
        src: ./Kickstarts/
        dest: /livecd-creator/FedoraRemix/
        rsync_path: "sudo -E rsync"
        times: false
        use_ssh_args: true
      become: true

    - name: Build Script
      ansible.builtin.copy:
        src: ./Prepare_Fedora_Remix_Build.yml
        dest: /livecd-creator/FedoraRemix/
      become: true

