---
- name: Setup System for Remix File Hosting
  hosts: localhost

### Play to get system ready for creating Fedora Remixes
### Designed to be run from localhost


  tasks:


## Create Directories

    - name: Install Packages for UCF Building
      ansible.builtin.yum:
        name: httpd
        state: latest
      become: true

    - name: Copy Files to Web Directory
      ansible.posix.synchronize:
        src: ./files
        dest: /var/www/html
      become: true

    - name: Copy Boot Theme to Web Directory
      ansible.posix.synchronize:
        src: ./files/boot/tm-fedora-remix
        dest: /var/www/html
      become: true  

    - name: Create Apache Configuration
      ansible.posix.synchronize:
        src: ./files/httpd_index.conf
        dest: /etc/httpd/conf.d/httpd_index.conf
      become: true

    - name: Create FedoraRemixCustomize Directory
      ansible.builtin.git:
        repo: https://github.com/tmichett/FedoraRemixCustomize.git
        dest: /var/www/html/FedoraRemixCustomize
      become: true

    - name: Create and Synchronize Scripts Directory
      ansible.posix.synchronize:
        src: ../YAD/scripts
        dest: /var/www/html/
      become: true

    - name: Copy YAD Files
      ansible.posix.synchronize:
        src: ../YAD/{{ item }}
        dest: /var/www/html
      become: true
      loop: 
        - Fedora_Remix_Apps.desktop
        - Fedora_Remix_Customize.sh


    - name: Enable HTTPD Service
      ansible.builtin.systemd:
        name: httpd
        enabled: true
        state: started
      become: true
