# Workflow name
name: Build PDF


# Controls when the workflow will run
# Workflow will run on a push event.
# Workflow won't be triggered to re-run based on the Gitauth token push
#on: 
  # This is a reusable workflow
#  workflow_dispatch:
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:

      # In this job, all steps begin with a name
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Podman Build Book
        run: bash ./adocpdf.sh Main.adoc

      - name: Podman Build HTML Website
        run: podman run --name adochtml --rm -v $(pwd):/tmp/ADOC_Work:Z quay.io/tmichett/adoc-html:latest Main.adoc

      - name: Copy all images to Docs Image Folder
        run: rsync ./images ./docs/

      - name: Commit and Add Book
        run: git config --global user.email "tmichett@redhat.com" && git config --global user.name "Travis Michette" && git add Main.pdf && mv Main.html ./docs/index.html && git add ./docs/index.html && git commit -m "Added new main.pdf and index.html"  && git push
